export const SITE_CONFIG = {
  name: "Gourmettazone by Kavita",
  logo: "/logo.png",
  tagline: "Artisan Cakes & Bakes in Ahmedabad | Creative Cooking With Kavita",
  whatsappNumber: "917574831119",
  whatsappDisplay: "+91 75748 31119",
  contactPerson: "Bharat Chavhan",
  address: "GF-55, Satyam Mall, Opp. Saman Complex, Nr. Mansi Cross Road, Vastrapur, Ahmedabad-380015",
  area: "Vastrapur, Ahmedabad",
  city: "Ahmedabad",
  state: "Gujarat",
  zipCode: "380015",
  neighborhoods: ["Vastrapur", "Mansi Cross Road", "Satellite", "Bopal", "Prahlad Nagar", "Bodakdev", "Thaltej"],
  instagram: "@gourmettazone",
  instagramUrl: "https://www.instagram.com/gourmettazone?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  instagramCooking: "@creativecookingwithkavitaa",
  email: "Gourmettazone@gmail.com",
  contactNumbers: ["+91 826429 2079", "+91 757483 1119"],
  openingHours: "Mon-Sun 09:00-21:00",
  googleMapsUrl: "https://maps.app.goo.gl/YourActualLinkIfAvailable",
};
